/**
 * Build Script - Generate Firebase Config from Environment Variables
 * 
 * This script reads environment variables (from .env.local or Vercel)
 * and generates config-generated.js with the actual Firebase credentials.
 * 
 * Runs at build time, keeping the app serverless while supporting env vars.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables from .env.local
const envPath = path.join(__dirname, '.env.local');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split('\n').forEach(line => {
    if (line && !line.startsWith('#')) {
      const [key, value] = line.split('=');
      if (key && value) {
        // Remove quotes if present
        process.env[key.trim()] = value.trim().replace(/^"|"$/g, '');
      }
    }
  });
  console.log('✓ Loaded environment variables from .env.local');
}

// Read environment variables
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || 'DEFAULT_API_KEY_PLACEHOLDER',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || 'universal-contribution-manager.firebaseapp.com',
  projectId: process.env.FIREBASE_PROJECT_ID || 'universal-contribution-manager',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || 'universal-contribution-manager.firebasestorage.app',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '10877815438',
  appId: process.env.FIREBASE_APP_ID || '1:10877815438:web:62bf12fcc99ccead3fd7df',
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || 'G-ZEBML1MZQ6'
};

const setupCode = process.env.SETUP_CODE || '';

// Generate the config file
const configContent = `/**
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by build.js from environment variables
 * This file is created at build time with Firebase credentials
 */

const GENERATED_FIREBASE_CONFIG = ${JSON.stringify(firebaseConfig, null, 2)};

const GENERATED_SETUP_CODE = ${JSON.stringify(setupCode)};`;


// Write the generated config file
const outputPath = path.join(__dirname, 'config-generated.js');

try {
  fs.writeFileSync(outputPath, configContent, 'utf8');
  console.log('✓ Firebase config generated successfully at config-generated.js');
  console.log('  API Key:', firebaseConfig.apiKey.substring(0, 20) + '...');
  console.log('  Project ID:', firebaseConfig.projectId);
  console.log('  Auth Domain:', firebaseConfig.authDomain);
} catch (error) {
  console.error('✗ Failed to generate config:', error.message);
  process.exit(1);
}
